### ISSUE TITLE
Can I create and sign monero transactions with this library?

### ISSUE THREAD

**Issue by ianpurton** [mymonero/mymonero-core-js#12]
I'm new to Monero but have a lot of experience with Bitcoin and Ethereum etc.

I'm looking for a library that will help me generate Monero transactions. So is it possible with this library to do the following..

1. Create a monero transaction. i.e. to address, amount to send. 
2. Sign the transaction ready for broadcast.

For 1, can you give some indications of the inputs required. i.e. in Bitcoin we would provide unspent outs, not sure if that's the same in Monero. 

Any help greatly appreciated.

**Comment by paulshapiro** [comment]
Hello, yes, please refer to the code, monero_sendingFunds_utils. Curious, was it unable to be found?
