### ISSUE TITLE
Fix regression in ability to input mnemonic with only few letters caused by language detection method (words in set)

### ISSUE THREAD

**Issue by paulshapiro** [mymonero/mymonero-core-js#14]
It would require being able to detect the language with word prefix letters, rather than whole words. Should be easy

**Comment by p0o** [comment]
Related to `encode` and `decode` functions? I didn't find any code related to language detection in the codebase so I guess you mean instead of giving the `wordset_name` you want to have a function to detect the language, am I right?

**Comment by paulshapiro** [comment]
@p0o, No, this issue pertains to a regression caused by the addition of language detection (see monero_wallet_utils.js/WordsetNameAccordingToMnemonicString). It needed to do a [prefix check](https://github.com/mymonero/mymonero-core-js/commit/e4366a708b8b29e8fbfd88155219325efe22a13e#diff-a5ddffdbae63f2568064a17563fe341dR106) instead of a naive "member is in set" (i.e. string equality) check.
