### ISSUE TITLE
Implement TypeScript

### ISSUE THREAD

**Issue by paulshapiro** [mymonero/mymonero-core-js#2]

**Comment by bradoyler** [comment]
Would you be open to using Webpack + Babel to transpile ES7?

**Comment by paulshapiro** [comment]
Feel free to try it out. We use webpack for a few other things. I was interested in ES6 transpilation some cross platform JS stuff for mymonero/mymonero-app-js a while ago but we're focusing on native now.

**Comment by paulshapiro** [comment]
After a few more seconds of thought, the main thing is that everything has to be rock solid and ES7 is somewhat experimental. But that condition is implicit to any PRs for core

**Comment by p0o** [comment]
I think we should first know what is the intended usage for this package. Right now everything is written with node modules which is kinda limiting it to be used only for backend. In my opinion it's not necessary and a simple webpack/babel setup can provide builds for browser and node while supporting quite safe non-experimental JS transformations like ES2015 including arrow functions, import/export, classes, spread .... which are very useful in terms of readability.

**Comment by paulshapiro** [comment]
> Right now everything is written with node modules which is kinda limiting it to be used only for backend. 

Not true.. The modules aren't explicitly for node. Besides, what you say about even being able to webpack is consistent with that. 

Cases in point... We already use webpack to prepare our other repo, mymonero-app-js, for [browser builds](https://github.com/mymonero/mymonero-app-js/blob/master/webpack.browser.prod.config.js), and we also use webpack on an index file which requires this mymonero-core-js's components to produce a [small JS bundle for iOS bridging](https://github.com/mymonero/mymonero-app-ios/tree/master/Modules/MyMoneroCore). 

In fact, this repo's code originally comes from JS written for the browser, so any node support has been additive. 😛

I'm curious, how did you hear about this repo if not by way of where we are using it?

> provide builds for browser and node while supporting quite safe non-experimental JS transformations like ES2015 including arrow functions, import/export, classes, spread 

I'm not opposed to new syntax (as you see we already use classes for many things in mymonero-app-js). I'm pleased to have someone add async/await support here unless I get to it first. But for now I don't see any need to enforce that webpack, or how webpacks and other transforms are done, as long as the source code itself does not prevent them from being done. 

> .... which are very useful in terms of readability

I'm open to concrete suggestions on improvements and modernizations. As we know, some parts of this code were written years ago. But I'd like to know which parts you find unreadable. To be honest unreadable code can be easily produced with e.g. arrow syntax. 

In any case, if you want to discuss that, can I trouble you to open another ticket? I'm going to keep this thread for actual discussion about Typescript itself. As a heads up, I may move your existing comments as they are not relevant to Typescript.

**Comment by paulshapiro** [comment]
(I removed the comments because they were off topic questions about ECMAScript version, after replying to them with answers and letting them know the comments would eventually be removed)

**Comment by paulshapiro** [comment]
Moving to C++ impl

**Comment by paulshapiro** [comment]
API may still be made typescript but it's no longer a priority
