### ISSUE TITLE
Add support for decoding and sending to subaddresses

### ISSUE THREAD

**Issue by paulshapiro** [mymonero/mymonero-core-js#3]

**Comment by moneromooo-monero** [comment]
Sending is the one that's really needed at first (ie, someone sends a subaddress for payment). Receiving is optional, since it's the recipient's choice.

**Comment by paulshapiro** [comment]
fyi https://github.com/moneroexamples/openmonero/commit/23ca56fe05bebdfa2002070d36b90f371f0bccf1#commitcomment-25578957

**Comment by paulshapiro** [comment]
@cryptochangements34 is the man: https://github.com/mymonero/mymonero-core-js/pull/10
