### ISSUE TITLE
package.json version behind

### ISSUE THREAD

**Issue by marceloneil** [mymonero/mymonero-core-js#36]
The version in package.json is `0.9.0`, even though the latest tag is `1.0.0` (this is for both the `master` and `develop` branches). It doesn't really make any sense to bump them now, but for the next tag it would be nice.

**Comment by paulshapiro** [comment]
Hmm where are you seeing that?

**Comment by paulshapiro** [comment]
Don't know how I missed that. Thanks

**Comment by marceloneil** [comment]
:+1: Keep that in mind for the next tag!

**Comment by paulshapiro** [comment]
Thanks
