### ISSUE TITLE
how to use my daemon address with this repo?

### ISSUE THREAD

**Issue by tarun1475** [mymonero/mymonero-core-js#42]
I want to develop a react native app using this core js monero library. Can i able to  do all the necessary functions without connecting to daemon and and develop secure mobile wallet in react native

**Comment by paulshapiro** [comment]
You use the response parser. You can also use the net client utils if you want. To send you want to pass in a hostedMoneroAPIClient. Please see our repo mymonero-app-js for full examples. We plan to do better documentation for this repo and welcome assistance, however the API is in flux at the present moment.
