### ISSUE TITLE
What to pass in monero_openalias_utils?

### ISSUE THREAD

**Issue by tarun1475** [mymonero/mymonero-core-js#44]
while using sendfunds function can somebody help me what to pass in monero_openalias_utils as a parameter?

**Comment by paulshapiro** [comment]
Hello tarun,

As I mentioned on my last reply, refer to mymonero/mymonero-app-js for a full example. Just do a project-wide search. You'll see it's very sensible.

Going forward, I ask that you not use Issues on these repositories to get personal help integrating the library to your app. If you would like integration assistance, please join us on freenode IRC in #mymonero or you can email us if you would like to explore using our hosting solution for which we can provide you more dedicated integration assistance.

Kindly
Paul

**Comment by tarun1475** [comment]
Okay thanks.
