### ISSUE TITLE
Where to find monero_amount_format_util file?

### ISSUE THREAD

**Issue by tarun1475** [mymonero/mymonero-core-js#45]
All mymonero apps use mymonero-core-js modules but there is a missing file monero_amount_format_utils that has been used in various modules while developing mymoneroapp for browser.

**Comment by paulshapiro** [comment]
Yes, correct, that's on the develop and cpp branches, meaning it's in development. Those functions are in cryptonote_utils in the old version. Very soon the develop branch will restabilize as I'm almost done with the related emscripten work.
