### ISSUE TITLE
TypeError: cnUtil.formatMoney is not a function

### ISSUE THREAD

**Issue by marceloneil** [mymonero/mymonero-core-js#50]
https://github.com/mymonero/mymonero-core-js/blob/92734c193a40b89d55822d62a2a49f39200e1e5e/cryptonote_utils/cryptonote_utils.js#L2919-L2921
`cnUtil` is undefined, as it is being called from within the definition of `cnUtil`.

**Comment by paulshapiro** [comment]
This is already fixed in the new branch given we factored money amount (JSBigInt) formatting. Thanks for the report and fix.

**Comment by marceloneil** [comment]
Feel free to close the issue/pr if it's considered resolved
