### ISSUE TITLE
derivation_to_scalar is removed in 1.1.2

### ISSUE THREAD

**Issue by gutenye** [mymonero/mymonero-core-js#68]
Is there an alternative way to do it in the new version. I used it for `decodeRct`.

**Comment by paulshapiro** [comment]
I would merge a PR with derivation_to_scalar if someone made it. I added generate_key_derivation, decodeRct, derive_public_key, create_wallet for the same reason but won't have an opportunity to add d2s for a couple/few weeks.

**Comment by gutenye** [comment]
@paulshapiro PR is made at #71
