### ISSUE TITLE
What is relationship with code running on mymonero.com?

### ISSUE THREAD

**Issue by moneroexamples** [mymonero/mymonero-core-js#81]
I compiled `mymonero-core-js` using current master and wanted to use them in openmonero along with new [send_coins.js](view-source:https://mymonero.com/js/controllers/send_coins.js?9). However, generated `MyMoneroCoreCpp_WASM.js` and `MyMoneroCoreCpp_WASM.wasm` are different than those used on mymonero website. And off course `send_coins.js` does not work with the files obtained by compilation of mymonero-core-js. So how the files on mymonero.com were compiled?

Also, is there any github repo for the files used in mymonero.com? It would simply tracking changes in the files.

**Comment by moneroexamples** [comment]
I think that mymonero-core.js. If you compare what is on mymonero.com (https://mymonero.com/js/lib/mymonero-core.js?3) and what mymonero-core-js generates (what it generates for me can be seen [here](https://paste.fedoraproject.org/paste/El2cAG1yN7uzHYkD-82aJA) ), big differences can be seen. 

Just in the first line differecese are obvious. mymonero.com has

```
!function(i,A){"object"==typeof exports&&
```

and from compilation we get:

```
var MyMoneroCoreCpp = (function() {
  var _scriptDir = typeof document !== 'undefined' && documen
```

When I use the generated code with the `send_coins.js?9` I get the following error:

```
angular.min.js:123 ReferenceError: mymonero_core_js is not defined
    at m.$scope.sendCoins (send_coins.js?7:185)
```

So I don't know why there are differences between what compiling mymonero-core-js produces, and what is on mymonero.com. Do I need to checkout some specific version or commit from mymonero-core-js to be in sync with mymonero.com?

**Comment by paulshapiro** [comment]
Mymonero-core.js which is used on mymonero.com right now is simply the product of running https://github.com/mymonero/mymonero-core-js/blob/master/bin/package_browser_js

**Comment by paulshapiro** [comment]
As for mymonero_core_js not being defined, you need to use a script tag to include mymonero-core.js

**Comment by moneroexamples** [comment]
Thanks! `bin/package_browser_js` solved the problem. 

btw, https://github.com/mymonero/mymonero-core-js/blob/master/README.md does not contain anything about this, thus I didn't know I should use it. Maybe could something about it added to README for futuer reference?

**Comment by paulshapiro** [comment]
Good idea! Thought i had it in there.

**Comment by moneroexamples** [comment]
Closing issue. Seems to be solved. 

Thanks again.
