### ISSUE TITLE
Thrown Error not clear.

### ISSUE THREAD

**Issue by babel5405** [mymonero/mymonero-core-js#87]
The error thrown on line 79 of MyMoneroCoreBridge.js seems to attempt to explain a solution, but doesn't provide information as to how to resolve the issue.

`throw "Unable to derive fullPath. Please pass locateFile() to bridge obj init."`

What does "Please pass locateFile() to bridge obj init." mean? The issue causing it to be thrown comes from scriptDirectory being an empty string. The message provided at line 65 of the same file  which console.warn'd at the same time also doesn't provide much in the way of useful information, because ${pathTo_cryptonoteUtilsDir} is undefined when it's used.

I should note that I'm attempting to use the library in an Electron App, I've tried using the library on both the render and main threads, and both used as a node module and compiled as if for a website with the compile scripts provided.

Versions: 
Node: 10.2.0
Electron: 3.0.9

**Comment by paulshapiro** [comment]
It means that your wasm / asm files are not in a standard / expected location. How are you attempting to bundle them?

**Comment by babel5405** [comment]
I tired both importing it into node's module system, and package_browser_js in /bin.

I've done more testing since I encountered the issue though, and it appears to be that since I'm trying to use it with electron the element "window" exists, and it's playing havoc on the platform detection, causing it to think it's web instead of node, which causes the path to the modules to never be filled.

I'm going to keep testing and see if I can come up with with a good solution, but un-minifying MyMoneroCoreCpp_WASM.js and hacking it so the platform is node instead of web fixes the problem and causes it to start working again. I don't think the source for that file is part of this repo though correct?

**Comment by paulshapiro** [comment]
Here, have a look at this. This is how we use MyMoneroCoreBridge in mymonero-app-js. We use IPC to talk to the main process.

https://github.com/mymonero/mymonero-app-js/blob/e2e85873c68df78449f814696883d4ff6cd5e1b7/local_modules/MoneroUtils/monero_utils.electron.web.js

which talks to

https://github.com/mymonero/mymonero-app-js/blob/e2e85873c68df78449f814696883d4ff6cd5e1b7/local_modules/MoneroUtils/__IPCSafe_remote_monero_utils.electron.js

and we include it like this in the renderer process

```
require('../../MoneroUtils/monero_utils.electron.web')({}).then(function(monero_utils)
{
})
```

**Comment by paulshapiro** [comment]
@babel5405 I'm going to disable emscripten catching uncaughtExceptions in Node.JS with NODEJS_CATCH_EXIT=0. Thanks

**Comment by paulshapiro** [comment]
That's been pushed

**Comment by babel5405** [comment]
Cool, that looks to be everything I encountered, and your answer on how you implemented in electron helped as well.
