### ISSUE TITLE
input sorts has error when  the number of inputs is larger than 10

### ISSUE THREAD

**Issue by bitcodernull** [mymonero/mymonero-core-js#9]
sources.sort(function (a, b) {
            return JSBigInt.parse(a.key_image, 16).compare(JSBigInt.parse(b.key_image, 16)) <0 ;
        });

should be：
sources.sort(function (a, b) {
            return JSBigInt.parse(a.key_image, 16).compare(JSBigInt.parse(b.key_image, 16)) * -1 ;
        });

**Comment by paulshapiro** [comment]
Hi @bitcodernull,

Yes, you're absolutely correct. Thank you

As to why it breaks at 10 inputs specifically, luigi and I are unsure, but hypothesize it may be down to browser-specific implementation of sort when a boolean value is (erroneously) returned from the sort comparator.

I'll go right ahead and apply the fix, but for future reference, I will gladly merge a PR.

Best,
Paul

**Comment by paulshapiro** [comment]
https://github.com/mymonero/mymonero-core-js/commit/08acb354746cda712191ed9c6bda5ff7be6815c9
