### ISSUE TITLE
Pure JS implementation for BulletProofV2 ( ringct v4)

### ISSUE THREAD

**Issue by jtomtan** [mymonero/mymonero-core-js#99]
Hi, I am from Ownbit Wallet team. We are integrating Monero. I'd like to know will there be a pure JS implementation for BulletProofV2 ? Just like cnUtil in cryptonote_utils.js ever. It can work until rightct v3. 

It's really hard for modern Wallets to integrate WASM.

**Comment by MartyHav** [comment]
you can use the asm.js fallback, its pure js.
